# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_imagedetails_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedetails',
            name='colors',
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='color1B',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='color1G',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='color1R',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='color2B',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='color2G',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='color2R',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='color3B',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='color3G',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='color3R',
            field=models.IntegerField(default=500),
        ),
    ]
