# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20170627_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetails',
            name='human',
            field=models.BooleanField(default=False),
        ),
    ]
